export const path = {
  root: () => '/',
  welcome: () => '/welcome',
  tasks: () => '/tasks',
  task: (id: string) => `/tasks/${id}`,
  newTask: () => '/tasks/new',
  editTask: (id: string) => `/tasks/${id}/edit`,
  users: () => '/users',
  projects: () => '/projects',
  project: (id: string) => `/projects/${id}`,
  newProject: () => '/projects/new',
  editProject: (id: string) => `/projects/${id}/edit`,
  tags: () => '/tags',
  newTag: () => '/tags/new',
}
